### PR TITLE
Multiline and sub-items

### LINKED ISSUE #31: Multiline is not handled correctly
Let's say I have the following changelog:
```markdown
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
### Changed
- Changed `f()` and `g()` into `h(b:bool)`.

  **The change is NOT backward compatible!!** 
  
  Please replace `.f()` -> `.h()`
  And replace `.g()` -> `.h(b=True)`

  Reason: There is a bug in `somelib` ...

  More: https://bugs.python.org/issueXXXXX
- Release note 2.

## [1.0.0] - 2017-04-10
### Deprecated
- Known issue 1 (1.0.0)
- Known issue 2 (1.0.0)

[Unreleased]: https://github.test_url/test_project/compare/v1.0.0...HEAD
[1.0.0]: https://github.test_url/test_project/releases/tag/v1.0.0
```

Rendered as so:

<details>

# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

### Changed
- Changed `f()` and `g()` into `h(b:bool)`.

  **The change is NOT backward compatible!!** 
  
  Please replace `.f()` -> `.h()`
  And replace `.g()` -> `.h(b=True)`

  Reason: There is a bug in `somelib` ...

  More: https://bugs.python.org/issueXXXXX
- Release note 2.

### Deprecated
- Known issue 1 (1.0.0)
- Known issue 2 (1.0.0)

[Unreleased]: https://github.test_url/test_project/compare/v1.0.0...HEAD
[1.0.0]: https://github.test_url/test_project/releases/tag/v1.0.0

</details>

If I run:
```python
import keepachangelog
print(keepachangelog.from_dict(keepachangelog.to_dict('CHANGELOG.md', show_unreleased=True)))
```

This is what I get:
```markdown
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
### Changed
- Changed `f()` and `g()` into `h(b:bool)`.
- The change is NOT backward compatible!!**
- Please replace `.f()` -> `.h()`
- And replace `.g()` -> `.h(b=True)`
- Reason: There is a bug in `somelib` ...
- More: https://bugs.python.org/issueXXXXX
- Release note 2.

## [1.0.0] - 2017-04-10
### Deprecated
- Known issue 1 (1.0.0)
- Known issue 2 (1.0.0)

[Unreleased]: https://github.test_url/test_project/compare/v1.0.0...HEAD
[1.0.0]: https://github.test_url/test_project/releases/tag/v1.0.0
```

Rendered as:

<details>

# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

### Changed
- Changed `f()` and `g()` into `h(b:bool)`.
- The change is NOT backward compatible!!**
- Please replace `.f()` -> `.h()`
- And replace `.g()` -> `.h(b=True)`
- Reason: There is a bug in `somelib` ...
- More: https://bugs.python.org/issueXXXXX
- Release note 2.

### Deprecated
- Known issue 1 (1.0.0)
- Known issue 2 (1.0.0)

[Unreleased]: https://github.test_url/test_project/compare/v1.0.0...HEAD
[1.0.0]: https://github.test_url/test_project/releases/tag/v1.0.0

</details>

As we can see, each line is managed as a new note.
```python
import keepachangelog, pprint
pprint.pprint(keepachangelog.to_dict('CHANGELOG.md', show_unreleased=True)['unreleased']['changed'])
```
```python
['Changed `f()` and `g()` into `h(b:bool)`.',
 'The change is NOT backward compatible!!**',
 'Please replace `.f()` -> `.h()`',
 'And replace `.g()` -> `.h(b=True)`',
 'Reason: There is a bug in `somelib` ...',
 'More: https://bugs.python.org/issueXXXXX',
 'Release note 2.']
```

### PR DESCRIPTION
**Pull request by Mulugruntz**
Fixes #31 

### Added
- The parsing engine is now Object-oriented and more flexible.
- Two new features:
  - **Multiline:** Items ( <-- such as this one) can now
    be written on several lines.
  - **Sub-items:** Items can now have sub-items.
    - Of any (reasonable) depth.

### Changed
- Release dates are parsed (several formats are supported). 
  When `to_dict()`, a unique format is chosen.
- When `to_raw_dict()`, release dates are kept "as-is" 
  (and `.lower()` is no longer applied)

### Fixed
- Change ordering is now deterministic
- When `to_raw_dict()`, empty lines are preserved.
- When semantic version exists, it is produced. Before, if 
  depended on some bugs (it was produced sometimes and not 
  other times, such as when the change was empty or if there 
  was only the link, something like that...). 
  This is now more consistent.

### CODE REVIEW

**Comment by Mulugruntz** [comment]
To be noted:
Even though it handles correctly multiline and sub-items, in order to be backward compatible the sub-items are flattened when `to_dict`.

As an example, this is how the `2.0.0.dev2` `CHANGELOG` entry looks like with the **2.0.0.dev1 parser**:

<details>

```json
"2.0.0.dev2": {
    "metadata": {
      "version": "2.0.0.dev2",
      "release_date": "2021-06-16",
      "semantic_version": {
        "major": 2,
        "minor": 0,
        "patch": 0,
        "prerelease": "dev2",
        "buildmetadata": null
      },
      "url": "https://github.com/Colin-b/keepachangelog/compare/v2.0.0.dev1...v2.0.0.dev2"
    },
    "changed": [
      "Release dates are parsed (several formats are supported).",
      "When `to_dict()`, a unique format is chosen.",
      "When `to_raw_dict()`, release dates are kept \"as-is\"",
      "(and `.lower()` is no longer applied)"
    ],
    "added": [
      "The parsing engine is now Object-oriented and more flexible.",
      "Two new features:",
      "Multiline:** Items ( <-- such as this one) can now",
      "be written on several lines.",
      "Sub-items:** Items can now have sub-items.",
      "Of any (reasonable) depth."
    ],
    "fixed": [
      "Change ordering is now deterministic",
      "When `to_raw_dict()`, empty lines are preserved.",
      "When semantic version exists, it is produced. Before, if",
      "depended on some bugs (it was produced sometimes and not",
      "other times, such as when the change was empty or if there",
      "was only the link, something like that...).",
      "This is now more consistent."
    ]
  },
```
</details>

And now with the **2.0.0.dev2 parser**:

<details>

```json
"2.0.0.dev2": {
    "metadata": {
      "version": "2.0.0.dev2",
      "release_date": "2021-06-16",
      "semantic_version": {
        "major": 2,
        "minor": 0,
        "patch": 0,
        "prerelease": "dev2",
        "buildmetadata": null
      },
      "url": "https://github.com/Colin-b/keepachangelog/compare/v2.0.0.dev1...v2.0.0.dev2"
    },
    "changed": [
      "Release dates are parsed (several formats are supported). \nWhen `to_dict()`, a unique format is chosen.",
      "When `to_raw_dict()`, release dates are kept \"as-is\" \n(and `.lower()` is no longer applied)"
    ],
    "added": [
      "The parsing engine is now Object-oriented and more flexible.",
      "Two new features:",
      "**Multiline:** Items ( <-- such as this one) can now\nbe written on several lines.",
      "**Sub-items:** Items can now have sub-items.",
      "Of any (reasonable) depth."
    ],
    "fixed": [
      "Change ordering is now deterministic",
      "When `to_raw_dict()`, empty lines are preserved.",
      "When semantic version exists, it is produced. Before, if \ndepended on some bugs (it was produced sometimes and not \nother times, such as when the change was empty or if there \nwas only the link, something like that...). \nThis is now more consistent."
    ]
  },

```

</details>

We can see that we'll need a new API to display the sub-items as... sub-items.
We could imagine `Encoder`s and `Decoder`s, such as `EncoderV1`, `EncoderV2`, etc... The current behaviour would be `V1` and the sub-items would only be correctly handled from `V2`.

This way, by default, it would use `V1` but people could specify a different `Encoder` &`Decoder`. Or even their own.

And it would make sense for `flask` and `starlette`, as it would be able to serve the different versions and not break backward compatibility.

**Comment by Mulugruntz** [comment]
I'll fix the Build another day.
Seems that I missed a few stuff with `mypy`.

**Comment by Colin-b** [comment]
Hello,

Thanks for contributing, can you tell me if you still plan to look at why build is failing?

**Comment by Mulugruntz** [comment]
Hi @Colin-b .

Yes, I'll try to find some time this week to look into that.
Sorry for the very big delay. Much has happened here and it was difficult to spend time on that.

**Comment by Colin-b** [comment]
Hello @Mulugruntz , tbh there is no rush at all :)

**Comment by samkearney** [comment]
Any chance of an update on getting this merged? Very nice library by the way 😄

**Comment by Colin-b** [comment]
> Any chance of an update on getting this merged? Very nice library by the way 😄

Hello @samkearney, Thanks for the kind word. 
I need to have a look at this one because it contains quite a lot of changes. I'll definitely try to have a go at it next week.

Best Regards

**Comment by Mulugruntz** [comment]
@Colin-b I'm currently looking into it, because I have some spare time these days.

**Comment by Mulugruntz** [comment]
@Colin-b About Travis, I get the message `Owner Colin-b does not have enough credits.`

Message can be seen there https://app.travis-ci.com/github/Colin-b/keepachangelog/requests

**Comment by Colin-b** [comment]
> @Colin-b About Travis, I get the message `Owner Colin-b does not have enough credits.`
> 
> Message can be seen there https://app.travis-ci.com/github/Colin-b/keepachangelog/requests

Yes I am migrating over to github actions for this reason. I'll do the change on develop branch right away

**Comment by Colin-b** [comment]
@Mulugruntz the change is done on develop branch. Build should run for each version of python (from 3.6 to 3.10)

**Comment by Mulugruntz** [comment]
@Colin-b 
It works!
https://github.com/Mulugruntz/keepachangelog/actions/runs/1769849313

However, it doesn't seem to show up here... maybe because it still recognizes Travis' authority?

**Comment by Mulugruntz** [comment]
I'll open a new PR.

**Pull request closed without merging**
